version: '3.8'

services:
  app:
    build: .
    container_name: fastapi_app
    restart: always
    ports:
      - "8005:8005"
    depends_on:
      - postgres
      - neo4j
    env_file:
      - .env
    volumes:
      - ./app:/app/app
    environment:
      - PORT=8005

  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  neo4j:
    image: neo4j:latest
    container_name: neo4j_db
    restart: always
    environment:
      NEO4J_AUTH: neo4j/password
      # Enable APOC plugins for advanced Neo4j operations
      NEO4J_apoc_export_file_enabled: "true"
      NEO4J_apoc_import_file_enabled: "true"
      NEO4J_apoc_import_file_use__neo4j__config: "true"
      NEO4J_dbms_security_procedures_unrestricted: "apoc.*"
    ports:
      - "7474:7474" # Neo4j Browser
      - "7687:7687" # Bolt Protocol for DB connections
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - ./neo4j/plugins:/plugins

volumes:
  postgres_data:
  neo4j_data:
  neo4j_logs:
